const assert = require('assert');
const fs = require('fs');

const wxml = fs.readFileSync('miniprogram/pages/frame/frame.wxml', 'utf8');
const wxss = fs.readFileSync('miniprogram/pages/frame/frame.wxss', 'utf8');
const js = fs.readFileSync('miniprogram/pages/frame/frame.js', 'utf8');
const homeWxml = fs.readFileSync('miniprogram/pages/home/home.wxml', 'utf8');
const homeJs = fs.readFileSync('miniprogram/pages/home/home.js', 'utf8');

assert(wxml.includes('activeTool'), 'tool state must be rendered');
assert(wxml.includes("activeTool==='template'"));
assert(wxml.includes("activeTool==='canvas'"));
assert(wxml.includes("activeTool==='frame'"));
assert(!wxml.includes("activeTool==='image'"), 'image controls must live in the picture panel');
assert(wxml.includes('图片缩放'));
assert(wxml.includes('onImageZoomChanging'));
assert(wxml.includes('min="50" max="200"'), 'image scaling must support zooming out and in');
assert(!wxml.includes('完整显示'), 'non-interactive fit copy should not be shown');
assert(wxml.includes('displayWidth') && wxml.includes('displayHeight'));
assert(wxml.includes('class="setting-content"'));
assert(!wxml.includes('scroll-y'), 'the settings panel must not require vertical scrolling');
assert(wxml.includes("{{panelExpanded?'收起':'展开'}}"), 'panel collapse must be available beside the tool tabs');
assert(wxml.includes('class="thumbnail-strip"'), 'the image strip must remain present');
assert(wxml.includes('id="preview"'), 'the preview canvas must remain present');
assert(wxml.includes('bindtap="exportAll"'), 'the export action must remain bound');
assert(wxml.includes("securityStatus==='rejected'") && wxml.includes("securityStatus==='error'"), 'security exceptions must remain visible on thumbnails');
assert(wxml.includes('showColorPicker') && wxml.includes('openColorPicker'), 'the color picker must remain available');
assert(wxml.includes('wx:for="{{innerFrameStyles}}"'), 'all inner frames must share one horizontal selector');
assert(!wxml.includes('基础内框') && !wxml.includes('片基内框'), 'inner frames must not be split into two selector rows');
assert(wxml.includes('frame-card-preview') && wxml.includes('item.previewAsset'), 'frame selector must render the style-owned production preview asset');
assert(wxml.includes('template-card-preview') && wxml.includes('src="{{item.previewAsset}}"'), 'template cards must use the same style-owned artwork as frame cards');
assert(!wxml.includes('template-photo') && !wxml.includes('template-edge'), 'template cards must not fall back to CSS mock artwork');
assert(!wxml.includes('启用内框'), 'the redundant inner-frame enable switch must not be rendered');
assert(wxml.includes('frameDetailsExpanded') && wxml.includes('toggleFrameDetails'), 'film-frame details must be collapsible');
assert(wxss.includes('.workspace') && wxss.includes('overflow: hidden'));
assert(wxss.includes('.preview-stage') && wxss.includes('.setting-sheet'));
assert(wxss.includes('--bf-accent') && wxss.includes('--bf-page'), 'gallery palette tokens must be defined');
assert(!wxss.includes('.main-panel'), 'legacy vertical editor shell should be removed');
assert(wxss.includes('.template-card, .frame-style-card { display: inline-flex; width: 92px'), 'template and inner-frame cards must share one size');
assert(wxss.includes('height: 58px'), 'template and inner-frame previews must share one height');
assert(wxss.includes('.detail-switch { transform: scale(.72)'), 'film detail switches must remain compact');
assert(!wxss.includes('.setting-sheet.template'), 'tool changes must not resize the preview stage');
assert(js.includes('measurePreviewViewport'));
assert(js.includes('panelScrollTop: 0'));
assert(js.includes("toolOptions: ['template', 'canvas', 'frame']"));
assert(js.includes('applyImageZoom'));
assert(js.includes('frameDetailsExpanded: false'), 'film-frame details should start collapsed');
assert(homeWxml.includes('/assets/frame-previews/emulsion-damage.png'), 'home must use a real product preview');
assert(!homeWxml.includes('feature-list') && !homeWxml.includes('specimen-photo'), 'home should not render feature-list or CSS mock artwork');
assert(homeJs.includes("url: '/pages/frame/frame'"), 'home must still enter the editor');
console.log('fixed workspace static checks passed');
